{{- if and .Values.enabled .Values.postgresAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cnpg-app-creds" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
type: {{ .Values.postgresAuth.type | default "kubernetes.io/basic-auth" }}
stringData:
  username: {{ .Values.postgresAuth.username | quote }}
  password: {{ .Values.postgresAuth.password | quote }}
{{- end }}
