{{- if and .Values.cnpg.enabled .Values.cnpg.postgresAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.postgresAuth.secretName }}
type: {{ .Values.cnpg.postgresAuth.type | default "kubernetes.io/basic-auth" }}
stringData:
  username: {{ .Values.cnpg.postgresAuth.username | quote }}
  password: {{ .Values.cnpg.postgresAuth.password | quote }}
{{- end }}
